// React
import { useEffect, useState } from "react";

// Nextjs
import Head from "next/head";

// CSS
import styles from "@/styles/Home.module.css";

// Supabase
import getReviews from "@/supabase/supabaseQueries";

export default function Home() {
	const [reviews, setReviews] = useState([]);

	useEffect(() => {
		const loadReviews = async () => {
			const reviews = await getReviews();
			setReviews(reviews);
		};
		loadReviews();
	}, []);

	return (
		<>
			<Head>
				<title>Rate My Course</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<>
					<h1>Create a review</h1>
					<p>Course Code</p>
					<input></input>
					<p>Rating</p>
					<input></input>
					<p>Comments</p>
					<input></input>
					<button>Post Review</button>
				</>
				<>
					<h1>Reviews</h1>
					{reviews.map((review, key) => {
						return (
							<div key={review.id}>
								<div>Course Code : {review.course_code}</div>
								<div>Rating : {review.rating}</div>
								<div>Comments : {review.comments}</div>
							</div>
						);
					})}
				</>
			</main>
		</>
	);
}
