// React
import { useEffect, useState } from "react";

// Nextjs
import Head from "next/head";
import Link from "next/link";

// CSS
import styles from "@/styles/Home.module.css";

// Components
import Navbar from "@/components/Navbar";

export default function Home() {
	return (
		<>
			<Head>
				<title>Rate My Course</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={styles.main}>
				<Navbar />
				<div className={styles.mainBody}>
					<h1 className={styles.homepageTitle}>
						View Peer Ratings, Search for a Course!
					</h1>
					<div className={styles.searchContainer}>
						<input
							className={styles.searchBar}
							type="text"
							placeholder="Search Course Name"
						/>
					</div>

					<div>
						<div className={styles.subSection}>
							<h1 className={styles.homepageTitle}>
								Top Rated Courses at UC Irvine
							</h1>
						</div>
						<div className={styles.subSection}>
							<h1 className={styles.homepageTitle}>
								Anteaters With Your Major Recommend...
							</h1>
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
